name: LocalStack Setup

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cloudformation:
    name: Deploy infrastructure using CloudFormation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Start LocalStack
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          DNS_ADDRESS: 0
        run: |
          pip install localstack awscli-local[ver1]
          docker pull localstack/localstack-pro:latest

          # Start LocalStack in the background
          localstack start -d

          # Wait 30 seconds for the LocalStack container to become ready before timing out
          echo "Waiting for LocalStack startup..."
          localstack wait -t 15

          echo "Startup complete"

      - name: Deploy on CloudFormation
        run: |
          make setup

      - name: Check deployed resources
        run: |
          sleep 20
          awslocal cloudformation describe-stacks --stack-name covid-lake-stack
